package com.sample.myrules

import com.galaxy.droolspractice.api.model.Message
 
rule "Hello World"
    when
        $m : Message( status == Message.HELLO, $myMessage : message )
    then
        System.out.println( "rules.sample.drl begin" );
        System.out.println( $myMessage);
        $m.setMessage( "Goodbye world" );
        $m.setStatus( Message.GOODBYE );
        update( $m );
        System.out.println( "rules.sample.drl end" );
end

